services:
  postgres:
    image: 'postgres:latest'
    container_name: oris_db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=19422
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    ports:
      - "5432:5432"