server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 19422
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

  freemarker:
    enabled: true
    template-loader-path: /WEB-INF/views
    suffix: .ftl

  mail:
    host: smtp.gmail.com
    username: "kononenkoyyulia@gmail.com"
    password: "mhudldwkluyyznxr"
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

mail:
  content: "Dear {name}, please follow the link below to verify your account: <a href={url}>VERIFY</a>"
  from: "kononenkoyyulia@gmail.com"
  sender: Test Application
  subject: Please verify your account